title: JumpCloud API Key V1 applications
url: https://docs.jumpcloud.com/1.0/applications
details: 'List systems
https://docs.jumpcloud.com/1.0/authentication-and-authorization/authentication-and-authorization-overview
'
commands:
- tool: curl
  command: '-H "x-api-key: APIKEYHERE" "https://console.jumpcloud.com/api/applications"'
  parameters:
  - description: APIKEY
    key: APIKEYHERE
    default_value:
regex: